[package]
name = "rust_blockchain_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = "0.3.20"
serde = "1.0.158"
serde_derive = "1.0.158"
serde_json = "1.0.94"
sha2 = "0.10.6"